### ISSUE TITLE
Не запустилось

### ISSUE THREAD

**Issue by pafftis** [kostyamat/rk3318_TvBox.-Home-Assistant.-Armbian-image#1]
Добрый день. Сделал следующим образом.
Залил multitool
скинул образ скачанный из архива разархивировал и получил файл: armbian24_HA17_clear.img.xz
Кинул его в папку images 
воткнул флешку \ воткнул питания в тв бокс.
Зашёл сделал фуло бэкап.
Сделал очистку памяти
Запустил установку образа вашего.
Установка прошла, выдернул пыталово, вынул флешку, воткнул питание, чёрный экран не чего не показывает на экране.

**Comment by kostyamat** [comment]
Добрий день. 
Який у вас бокс? Процесор точно RK3318, або RK3328? Бо китайці під одною назвою роблять на чому бог пошле. Якраз на якомусь трохи новішому процесорі таке і відбувається - зображення з'являється тільки якщо монітор/телевізор під'єднати вже після загрузки системи, або взагалі ніколи. Але так, чи інакше, на новіших процесорах ця збірка не юзабельна, там будуть проблеми не тільки з зображенням. 

Відновіть бекап, і точно перевірте тип процесора.

**Comment by pafftis** [comment]
Я прочёл, что вроде как на процессор нет особого влияния, типа rk3318 или rk3328, это как i3 с одной частотой и i3 с другой. По поводу блютуза, удалось сделать.
Так-же удалось заставить работать Bluetooth на приставке. Как оказалось, все довольно просто.
В данной приставке у меня используется чип Wi-fi и Bluetooth SP2734C – он же копия чипа AP6334.
Зная эту информацию нужно сделать следующее.
Запустить Armbian-config (при условии, что он у Вас уже установлен ранее)
Armbian-config
Там выбрать System ->Hardware-> и поставить галочку у  rk3318-box-wlan-ap6334
Далее предложит перезапустить систему, перезапускаем.
Далее снова запускаем Armbian-config
Armbian-config
Далее заходив в Network -> BT install после чего установятся компоненты необходимые для работы с блютуз. И после блютуз начнет работать.
Проверить можно командой:
hciconfig -a
Если ничего не выводит, то блютуза нет. А если выводит, что-то типо этого, то все работает корректно.
