### ISSUE TITLE
Все работает

### ISSUE THREAD

**Issue by vid8266** [kostyamat/rk3318_TvBox.-Home-Assistant.-Armbian-image#2]
Нужно поправить WI_FI и Блютус работает

**Comment by kostyamat** [comment]
У мене навпаки, wifi працює, а bluetooth ні. Схоже якась специфіка пов'язана з ревізіями бокса.

**Comment by vid8266** [comment]
Для запуска Bluetooth нужно сделать как описано тут
https://psenyukov.ru/установка-armbian-и-home-assistant-на-tv-box-h96-max-на-процессоре-rockchip-rk33/
WIFI файл тоже заменить как описано. Все заработает и HA увидит блютус.

**Comment by kostyamat** [comment]
Справа в тому, що файл я заміняв. І вибір в типу віфі в armbian-config також робив. Але bluetooth в мене так і не запрацював, а wifi працювало й без заміни файлу. Є все ж якийсь нюанс саме з моїм боксом. Тому в цей образ я добавив повний набір bluetooth firmaware, завдяки цьому працюють багато зовнішніх свистків блютуз, але не вбудований.

**Comment by vid8266** [comment]
Скорее всего все зависит от коробки! у меня H96Max v1.4 4x64 Gb. Там у китайцев в одной партии могут быть проблемы с emmc (разное количество секторов) и прошивки не залетают. Могут быть нюансы с Блютус и т.д. Удачи...
